### ISSUE TITLE
Erro na instalação

### ISSUE THREAD

**Issue by erivansilva** [viniciusfbb/skia4delphi#19]
Boa tarde.

Eu instalei o Skia para teste, no entanto, ele está apresentando o seguinte erro:
![Skia4Delphi](https://user-images.githubusercontent.com/69176863/145244626-469ced6e-4ddc-4461-b4aa-416101a1417b.png)

Já fiz a instalação pelos três métodos (**Skia4Delphi_2.0.1_Setup.exe**, **Manual** e via  **GetIt**).

Nota: A versão do delphi: 10.4 Update 2 Community Edition.

Atenciosamente.

**Comment by viniciusfbb** [comment]
Boa tarde @erivansilva, e muito obrigado por reportar o problema!

Pode ser que o package que o seu RAD Studio não está localizando seja fruto de uma instalação incompleta (por exemplo um passo errado da instalação manual). Eu também não recomendo a instalação via GetIt no 10.4, a embarcadero só iria disponibilizar no RAD Studio 11.

Então faça a instalação pelo instalador (Skia4Delphi_2.0.1_Setup.exe). Siga os passos para uma possível solução do seu problema:

1) Desinstale via GetIt o Skia4Delphi.
2) Pelo painel de controle, desinstale o Skia4Delphi.
3) Remova o diretório da instalação manual que você fez. (Não use o nome deste diretório na nova instalação)
4) Execute o Skia4Delphi_2.0.1_Setup.exe normalmente (não precisa ser como administrador, desde que use a pasta padrão que o instalador indica). Lembre-se de não usar o mesmo diretório da instalação manual.

**Comment by erivansilva** [comment]
@viniciusfbb, eu consegui. 

Eu fiz o passo a passo depois tive de ir até o diretório Packages\Delphi10Sydney e fiz a compilação e instalação.

Agora está normal.

Muito obrigado.

Eu tinha me esquecido, **Parabéns pelo projeto**.

**Comment by viniciusfbb** [comment]
@erivansilva Vou fechar o issue mas colocarei no To-Do a melhoria do instalador para a próxima versão. Outras pessoas também relataram dificuldades.
