### ISSUE TITLE
Windows 11 Delphi 11 Apparent Incompatibilities

### ISSUE THREAD

**Issue by TheOriginalBytePlayer** [viniciusfbb/skia4delphi#23]
I just tried to setup my Delphi 11 to work on a project using Skia4Delphi on a Windows 11 laptop with an Intel Iris Graphics card, and unfortunately the display is completely unusable within the IDE--it seems to be a redraw problem of some sort that makes it so that where the Skia SVG should be is just a mishmash of underlying code and repeated image fragments that makes it impossible to work within the IDE using a Skia Enabled project.

I did do a test build and while the IDE's display is completely unusable, it does appear that the built app runs okay.  Still this is a major issue for me. I can attach screen shots if that would be helpful.

**Comment by viniciusfbb** [comment]
Hi @TheOriginalBytePlayer! Thank you very much for reporting the issue.

We need more information. Could you send us a screenshot of the problem? Does the problem occur in VCL, FMX, or both? Does the problem only occur with TSkSVG?

**Comment by TheOriginalBytePlayer** [comment]
Okay, I'll add a screen shot -- I'm only using it with FMX so I don't know about VCL...

**Comment by TheOriginalBytePlayer** [comment]
![2021-12-20](https://user-images.githubusercontent.com/18058224/146852822-991ba93c-8eb9-4d29-8b9b-bba3a338b911.png)
Here's the code and when I switch to the design view it looks like this...
![2021-12-20 (1)](https://user-images.githubusercontent.com/18058224/146852984-6db66c19-535e-45ba-a094-4093f20a5b36.png)
As you can see, a whole section of it should be showing an image but is instead showing code.  In comparison, it should look like this:
![image](https://user-images.githubusercontent.com/18058224/146853267-4bcfb30b-85b3-4658-a67f-d2736b1645fe.png)

**Comment by TheOriginalBytePlayer** [comment]
By the way, I thought it might have something to do with a conflict in style sheets but I deleted the style book and it didn't make any differenced -- well, aside from changing the overall look, but the problems were still the same.

**Comment by viniciusfbb** [comment]
When did this start to happen? What skia components do you use in this form? Do you use any skia components in the style?

**Comment by TheOriginalBytePlayer** [comment]
My main development machine is a Windows 10 machine on which it works fine.  I was trying to setup my Windows 11 notebook so I would work on the project while not in the office and it happened immediately when I started to try to work.  So it's never worked on my Win 11 notebook.  I have the latest updates and uninstalled and reinstalled skia based on the latest version available on Github.

I have no skia components in the style -- I just thought since they are both involved in the display it might be some kind of conflict.  I do however, have custom Skia Components in my object library and on the form.  The camera controls in the bottom of the screen (the area that isn't displaying) is a TskSVG background with five custom controls in it.

**Comment by TheOriginalBytePlayer** [comment]
Actually, I have an update on this.  It apparently has nothing to do with Skia per se.  I decided to test it with a brand new project because I had the theory that the issue might have been something to do with the Skia rendering context being mostly off screen but when I created a completely blank document then I ran into the same kind of issues.  So I went into my display settings and changed it from 125% scaling to 100% and the whole issue went away.

Not very impressive on Delphi's front--especially as they make such a big deal about being high DPI aware, but at least I have a work around

**Comment by viniciusfbb** [comment]
Ok. I still can't share my experience with windows 11, as my main development is still on windows 10. But from what I saw in the quality center, the IDE still has several bugs, not only related to Windows 11, but to Alexandria too. It is important that once you understand the problem better, you report it either here (if it really is the skia) or to the quality center (if it really is the IDE).

For now I will close the issue. But as soon as you have more information, feel free to report it to us.
