### ISSUE TITLE
Projeto

### ISSUE THREAD

**Issue by erivansilva** [viniciusfbb/skia4delphi#31]
Boa noite.

O projeto ainda está em desenvolvimento.

Atenciosamente.

**Comment by viniciusfbb** [comment]
Olá @erivansilva!

Sim, o projeto está em pleno desenvolvimento, inclusive em poucos dias lançaremos uma grande atualização, o release v3.
A versão que existe atualmente, a v2.0.1, é estável e já pode ser usada em produção, mas a essa altura vale a pena ligar o "Watch" do projeto e esperar a nova versão.

Atenciosamente,
