### ISSUE TITLE
Possível problema com SkLottieAnimation

### ISSUE THREAD

**Issue by arbsis** [viniciusfbb/skia4delphi#32]
https://user-images.githubusercontent.com/44527776/151907547-b11e9885-c52e-4c87-95bf-3a5199b7e073.mp4

[XE11.zip](https://github.com/viniciusfbb/skia4delphi/files/7975633/XE11.zip)

Olá, estou achando os componentes fantásticos, mas tenho uma dúvida/problema.
Se eu coloco o SkLottieAnimation dentro de um TPanel ele tem um comportamento estranho de "flash", é assim mesmo? O componente só funciona bem se estiver dentro do Form?

**Comment by viniciusfbb** [comment]
Olá @arbsis, fico feliz que esteja gostando!

No Vcl, o controle parent do TSkLottieAnimation precisa ter o "ParentBackground = False" ou ser um form, para que o flickering não ocorra.

Por conta disso, estamos refazendo o controle do lottie. Lançaremos na versão 3.0.0 (a próxima versão que será lançada em menos de 1 semana), algumas melhorias de desempenho, que serão percebidas principalmente quando houver várias animações rodando ao mesmo tempo.

Atenciosamente, Vinícius F.
