### ISSUE TITLE
Error to intall the component in delphi 10.4.2

### ISSUE THREAD

**Issue by samuelsoarees** [viniciusfbb/skia4delphi#7]
The log with the description of the error is below:
[Build.Logs.txt](https://github.com/viniciusfbb/skia4delphi/files/7225412/Build.Logs.txt)

**Comment by viniciusfbb** [comment]
Hi Samuel!

This is a Delphi problem when compiling by MSBuild when your Library Path contains too many paths and/or too long paths, so the total character limit of 32000 is reached (in your case there are 36498 characters).

In short, you have a lot of components installed and no command line compilation will work. Delphinus, Boss, Final Builder, and many libraries that compile via command line will not work on your computer.

**Solutions**

1) Reduce the total size of paths:

    - Uninstall libraries you don't use and remove them from Library path.
    - Change the installation destination of some libraries to shorter paths.

2) You can manually install Skia4Delphi as this problem only occurs in compilations via command line. See [documentation for manual installation](https://github.com/viniciusfbb/skia4delphi/blob/main/Documents/INSTALLATION.md).

**Comment by samuelsoarees** [comment]
Ok, i will try install manually. Thanks

**Comment by viniciusfbb** [comment]
Just a information:
If you uninstall ACBr, which currently in the path "C:\Componentes_Rio\ACBr" and install it in the folder "C:\ACBr" will reduce to 29500 thousand characters and the compilations via MSBuild will work again.

**Comment by samuelsoarees** [comment]
OK, i will try to install like that. Thank you soo much

**Comment by samuelsoarees** [comment]
I tried again and made the changes and it worked. Thanks for your help
