### ISSUE TITLE
Weight of SO

### ISSUE THREAD

**Issue by kazuser** [viniciusfbb/skia4delphi#8]
Thanks for skia4delphi — looks great!

One question: is there a way to reduce the size of SO-files if I only need Lottie support for Android? I have an app ~15MB. Now with SO-files its weight is ~20+MB :(

**Comment by viniciusfbb** [comment]
Hi @kazuser,

The best way to reduce the size would be through static linking. We plan to implement static linking on all non-windows platforms in the future. Now this is not our current focus.
